# Generated by Django 4.1.4 on 2023-09-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('IDp', models.CharField(max_length=10)),
                ('Type', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
