# Generated by Django 4.1.4 on 2023-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdacceditationapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='IDp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Photo',
            field=models.ImageField(default='anonymous.png', null=True, upload_to=''),
        ),
    ]
