# Generated by Django 4.2.5 on 2023-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkdacceditationapi', '0002_alter_participant_idp_alter_participant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='autoType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
